/** ISO 3166-1 alpha-2 to alpha-3 mapping (used to convert Nominatim country codes to map polygon ids). */
const ALPHA2_TO_ALPHA3: Record<string, string> = {
  AF: "AFG", AX: "ALA", AL: "ALB", DZ: "DZA", AS: "ASM", AD: "AND", AO: "AGO", AI: "AIA",
  AQ: "ATA", AG: "ATG", AR: "ARG", AM: "ARM", AW: "ABW", AU: "AUS", AT: "AUT", AZ: "AZE",
  BS: "BHS", BH: "BHR", BD: "BGD", BB: "BRB", BY: "BLR", BE: "BEL", BZ: "BLZ", BJ: "BEN",
  BM: "BMU", BT: "BTN", BO: "BOL", BQ: "BES", BA: "BIH", BW: "BWA", BV: "BVT", BR: "BRA",
  IO: "IOT", BN: "BRN", BG: "BGR", BF: "BFA", BI: "BDI", CV: "CPV", KH: "KHM", CM: "CMR",
  CA: "CAN", KY: "CYM", CF: "CAF", TD: "TCD", CL: "CHL", CN: "CHN", CX: "CXR", CC: "CCK",
  CO: "COL", KM: "COM", CG: "COG", CD: "COD", CK: "COK", CR: "CRI", CI: "CIV", HR: "HRV",
  CU: "CUB", CW: "CUW", CY: "CYP", CZ: "CZE", DK: "DNK", DJ: "DJI", DM: "DMA", DO: "DOM",
  EC: "ECU", EG: "EGY", SV: "SLV", GQ: "GNQ", ER: "ERI", EE: "EST", SZ: "SWZ", ET: "ETH",
  FK: "FLK", FO: "FRO", FJ: "FJI", FI: "FIN", FR: "FRA", GF: "GUF", PF: "PYF", TF: "ATF",
  GA: "GAB", GM: "GMB", GE: "GEO", DE: "DEU", GH: "GHA", GI: "GIB", GR: "GRC", GL: "GRL",
  GD: "GRD", GP: "GLP", GU: "GUM", GT: "GTM", GG: "GGY", GN: "GIN", GW: "GNB", GY: "GUY",
  HT: "HTI", HM: "HMD", VA: "VAT", HN: "HND", HK: "HKG", HU: "HUN", IS: "ISL", IN: "IND",
  ID: "IDN", IR: "IRN", IQ: "IRQ", IE: "IRL", IM: "IMN", IL: "ISR", IT: "ITA", JM: "JAM",
  JP: "JPN", JE: "JEY", JO: "JOR", KZ: "KAZ", KE: "KEN", KI: "KIR", KP: "PRK", KR: "KOR",
  KW: "KWT", KG: "KGZ", LA: "LAO", LV: "LVA", LB: "LBN", LS: "LSO", LR: "LBR", LY: "LBY",
  LI: "LIE", LT: "LTU", LU: "LUX", MO: "MAC", MG: "MDG", MW: "MWI", MY: "MYS", MV: "MDV",
  ML: "MLI", MT: "MLT", MH: "MHL", MQ: "MTQ", MR: "MRT", MU: "MUS", YT: "MYT", MX: "MEX",
  FM: "FSM", MD: "MDA", MC: "MCO", MN: "MNG", ME: "MNE", MS: "MSR", MA: "MAR", MZ: "MOZ",
  MM: "MMR", NA: "NAM", NR: "NRU", NP: "NPL", NL: "NLD", NC: "NCL", NZ: "NZL", NI: "NIC",
  NE: "NER", NG: "NGA", NU: "NIU", NF: "NFK", MK: "MKD", MP: "MNP", NO: "NOR", OM: "OMN",
  PK: "PAK", PW: "PLW", PS: "PSE", PA: "PAN", PG: "PNG", PY: "PRY", PE: "PER", PH: "PHL",
  PN: "PCN", PL: "POL", PT: "PRT", PR: "PRI", QA: "QAT", RE: "REU", RO: "ROU", RU: "RUS",
  RW: "RWA", BL: "BLM", SH: "SHN", KN: "KNA", LC: "LCA", MF: "MAF", PM: "SPM", VC: "VCT",
  WS: "WSM", SM: "SMR", ST: "STP", SA: "SAU", SN: "SEN", RS: "SRB", SC: "SYC", SL: "SLE",
  SG: "SGP", SX: "SXM", SK: "SVK", SI: "SVN", SB: "SLB", SO: "SOM", ZA: "ZAF", GS: "SGS",
  SS: "SSD", ES: "ESP", LK: "LKA", SD: "SDN", SR: "SUR", SJ: "SJM", SE: "SWE", CH: "CHE",
  SY: "SYR", TW: "TWN", TJ: "TJK", TZ: "TZA", TH: "THA", TL: "TLS", TG: "TGO", TK: "TKL",
  TO: "TON", TT: "TTO", TN: "TUN", TR: "TUR", TM: "TKM", TC: "TCA", TV: "TUV", UG: "UGA",
  UA: "UKR", AE: "ARE", GB: "GBR", US: "USA", UM: "UMI", UY: "URY", UZ: "UZB", VU: "VUT",
  VE: "VEN", VN: "VNM", VG: "VGB", VI: "VIR", WF: "WLF", EH: "ESH", YE: "YEM", ZM: "ZMB",
  ZW: "ZWE", XK: "XKX",
};

export function alpha2ToAlpha3(alpha2: string | undefined | null): string | null {
  if (!alpha2) return null;
  return ALPHA2_TO_ALPHA3[alpha2.toUpperCase()] ?? null;
}

/** ISO 3166-1 alpha-3 to display name mapping (comprehensive). */
const ALPHA3_TO_NAME: Record<string, string> = {
  AFG: "Afghanistan", ALB: "Albania", DZA: "Algeria", ASM: "American Samoa", AND: "Andorra",
  AGO: "Angola", AIA: "Anguilla", ATG: "Antigua & Barbuda", ARG: "Argentina", ARM: "Armenia",
  ABW: "Aruba", AUS: "Australia", AUT: "Austria", AZE: "Azerbaijan",
  BHS: "Bahamas", BHR: "Bahrain", BGD: "Bangladesh", BRB: "Barbados", BLR: "Belarus",
  BEL: "Belgium", BLZ: "Belize", BEN: "Benin", BMU: "Bermuda", BTN: "Bhutan",
  BOL: "Bolivia", BIH: "Bosnia & Herzegovina", BWA: "Botswana", BRA: "Brazil",
  BRN: "Brunei", BGR: "Bulgaria", BFA: "Burkina Faso", BDI: "Burundi",
  CPV: "Cape Verde", KHM: "Cambodia", CMR: "Cameroon", CAN: "Canada", CYM: "Cayman Islands",
  CAF: "Central African Republic", TCD: "Chad", CHL: "Chile", CHN: "China", COL: "Colombia",
  COM: "Comoros", COG: "Congo", COD: "DR Congo", COK: "Cook Islands", CRI: "Costa Rica",
  CIV: "Ivory Coast", HRV: "Croatia", CUB: "Cuba", CUW: "Curacao", CYP: "Cyprus",
  CZE: "Czech Republic", DNK: "Denmark", DJI: "Djibouti", DMA: "Dominica", DOM: "Dominican Republic",
  ECU: "Ecuador", EGY: "Egypt", SLV: "El Salvador", GNQ: "Equatorial Guinea", ERI: "Eritrea",
  EST: "Estonia", SWZ: "Eswatini", ETH: "Ethiopia",
  FJI: "Fiji", FIN: "Finland", FRA: "France", PYF: "French Polynesia",
  GAB: "Gabon", GMB: "Gambia", GEO: "Georgia", DEU: "Germany", GHA: "Ghana",
  GRC: "Greece", GRL: "Greenland", GRD: "Grenada", GTM: "Guatemala", GIN: "Guinea",
  GNB: "Guinea-Bissau", GUY: "Guyana",
  HTI: "Haiti", HND: "Honduras", HKG: "Hong Kong", HUN: "Hungary",
  ISL: "Iceland", IND: "India", IDN: "Indonesia", IRN: "Iran", IRQ: "Iraq",
  IRL: "Ireland", ISR: "Israel", ITA: "Italy", JAM: "Jamaica",
  JPN: "Japan", JOR: "Jordan", KAZ: "Kazakhstan", KEN: "Kenya", KIR: "Kiribati",
  PRK: "North Korea", KOR: "South Korea", KWT: "Kuwait", KGZ: "Kyrgyzstan",
  LAO: "Laos", LVA: "Latvia", LBN: "Lebanon", LSO: "Lesotho", LBR: "Liberia",
  LBY: "Libya", LIE: "Liechtenstein", LTU: "Lithuania", LUX: "Luxembourg",
  MAC: "Macau", MDG: "Madagascar", MWI: "Malawi", MYS: "Malaysia", MDV: "Maldives",
  MLI: "Mali", MLT: "Malta", MHL: "Marshall Islands", MRT: "Mauritania", MUS: "Mauritius",
  MEX: "Mexico", FSM: "Micronesia", MDA: "Moldova", MCO: "Monaco", MNG: "Mongolia",
  MNE: "Montenegro", MAR: "Morocco", MOZ: "Mozambique", MMR: "Myanmar",
  NAM: "Namibia", NRU: "Nauru", NPL: "Nepal", NLD: "Netherlands", NCL: "New Caledonia",
  NZL: "New Zealand", NIC: "Nicaragua", NER: "Niger", NGA: "Nigeria", MKD: "North Macedonia",
  NOR: "Norway", OMN: "Oman",
  PAK: "Pakistan", PLW: "Palau", PSE: "Palestine", PAN: "Panama", PNG: "Papua New Guinea",
  PRY: "Paraguay", PER: "Peru", PHL: "Philippines", POL: "Poland", PRT: "Portugal",
  PRI: "Puerto Rico", QAT: "Qatar",
  ROU: "Romania", RUS: "Russia", RWA: "Rwanda",
  KNA: "St Kitts & Nevis", LCA: "St Lucia", VCT: "St Vincent", WSM: "Samoa",
  STP: "Sao Tome & Principe", SAU: "Saudi Arabia", SEN: "Senegal", SRB: "Serbia",
  SYC: "Seychelles", SLE: "Sierra Leone", SGP: "Singapore", SVK: "Slovakia", SVN: "Slovenia",
  SLB: "Solomon Islands", SOM: "Somalia", ZAF: "South Africa", SSD: "South Sudan",
  ESP: "Spain", LKA: "Sri Lanka", SDN: "Sudan", SUR: "Suriname", SWE: "Sweden",
  CHE: "Switzerland", SYR: "Syria",
  TWN: "Taiwan", TJK: "Tajikistan", TZA: "Tanzania", THA: "Thailand", TLS: "Timor-Leste",
  TGO: "Togo", TON: "Tonga", TTO: "Trinidad & Tobago", TUN: "Tunisia", TUR: "Turkey",
  TKM: "Turkmenistan", TCA: "Turks & Caicos", TUV: "Tuvalu",
  UGA: "Uganda", UKR: "Ukraine", ARE: "UAE", GBR: "United Kingdom", USA: "United States",
  URY: "Uruguay", UZB: "Uzbekistan", VUT: "Vanuatu", VEN: "Venezuela", VNM: "Vietnam",
  YEM: "Yemen", ZMB: "Zambia", ZWE: "Zimbabwe", XKX: "Kosovo",
};

/** Convert ISO-3 alpha-3 code to a human-readable country name. */
export function alpha3ToCountryName(alpha3: string | undefined | null): string | null {
  if (!alpha3) return null;
  return ALPHA3_TO_NAME[alpha3.toUpperCase()] ?? null;
}
